### PR TITLE
Encode hash_name with encodeURIComponent

### PR DESCRIPTION
**Pull request by FlaminSarge**
Fixes quite a few cases where items with '#' or other characters in the name get incorrect links

### CODE REVIEW

**Comment by JoiNNN** [comment]
Can you please provide an example for this?

**Comment by FlaminSarge** [comment]
E.g. the following item:
http://steamcommunity.com/id/flaminsarge/inventory#440_2_5674660100
named `Mann Co. Supply Munition Series #92`
causes EnhancedSteam to make a request to `http://steamcommunity.com/market/priceoverview/?currency=1&appid=440&market_hash_name=Mann%20Co.%20Supply%20Munition%20Series%20`
which is missing a url-encoded '%2392' at the end at the end of it; the request fails and EnhancedSteam throws an error, failing to get the quicksell price.
The "View in Community Market" link also uses '#' instead of url-encoded '%23', pointing to 
`http://steamcommunity.com/market/listings/440/Mann%20Co.%20Supply%20Munition%20Series%20#92` instead of
`http://steamcommunity.com/market/listings/440/Mann%20Co.%20Supply%20Munition%20Series%20%2392`

**Comment by FlaminSarge** [comment]
Need any more info?

**Comment by JoiNNN** [comment]
Thanks for reporting, I could replicate the issue and can confirm using `encodeURIComponent` fixes it.
Can you please direct your PR to the "dev" branch? Make sure to always work on and submit your changes and PRs to "dev".

**Comment by FlaminSarge** [comment]
Done.

**Pull request merged**
