### PR TITLE
Replace incorrect symbols for `Ruble`

### PR DESCRIPTION
**Pull request by ShockwaveNN**
There was symbols `pуб`, first letter was English letter P
I change it to `руб`, first letter is russian letter Р (эр, рубль)

### CODE REVIEW

**Comment by ShockwaveNN** [comment]
@jshackles any news on it?
It pretty simple PR, I almost 100% sure it will not break anything

**Comment by jshackles** [comment]
The issue I'm experiencing when running this is that some of this code is used for pattern detection on the Steam store.  For example, the currency_symbol_to_type () function takes data from the page and parses it into the correct currency type.  Because the Steam store uses the English letter P (rather than the Russian letter) these functions no longer work as intended.

**Comment by ShockwaveNN** [comment]
Sorry, my bad.
So problem in thirst place, that Valve use incorrect symbol on original, non alternated web Steam?

**Comment by jshackles** [comment]
That is correct.

If and when Valve updates the store to use the correct symbol, I will reopen this PR.

**Comment by ShockwaveNN** [comment]
Fair enough

**Pull request closed without merging**
