### PR TITLE
FIX: Unreleased games show NaN% in wishlist scores

### PR DESCRIPTION
**Pull request by orestisf1993**
Before: https://i.imgur.com/XeKFhPw.png
After: https://i.imgur.com/ULpMxMX.png

### CODE REVIEW

**Comment by jshackles** [comment]
An excellent and easy fix - thank you :+1:

**Comment by ACeregini** [comment]
I'm still getting this. I was about to create a new issue but I think updating this is more appropriate. 
Games with 0 reviews are marked by the red thumb down of negativity, and the following label: "Nan% of the 0 user reviews for this game are positive".
This happens - obviously - for wishlisted games that are yet to be released. Here's an example:
2017-10-23-10-35-steamcommunity com

**Comment by orestisf1993** [comment]
I think that this commit (dea1051095eb2f468894772d972a265fb6d6a938) is still in the [dev](https://github.com/jshackles/Enhanced_Steam/tree/dev) branch. Did you try with the dev branch?

**Comment by ACeregini** [comment]
No idea what that really means sorry

**Comment by jshackles** [comment]
@ACeregini it means that it will be released in the upcoming 9.6 version.  This will be happening soon.

**Comment by ACeregini** [comment]
Oh thanks

**Pull request merged**
