### PR TITLE
implement wishlist sorting by currency value of discount

### PR DESCRIPTION
**Pull request by wchristian**
This is only a very rough implementation of it, with very crude copy-pasting and adapting of the necessary bits to make it work. Please have a look and let me know if you'd like anything changed right now, and after that, or when you don't see anything obvious, i'm open to deduplicating it and the discount sorting function; or you can merge immediately. However you like it.

image

### CODE REVIEW

**Comment by jshackles** [comment]
I'm not sure I understand how this is different from the already available discount sort on wishlist pages.  Can you provide a specific example of where this would be useful?

**Comment by wchristian** [comment]
It helps bring games to the top where one can save the maximum amount of $currency per purchase.

Compare:

Sort by price: http://i.imgur.com/uRZM5bf.png
Sort by discount: http://i.imgur.com/bARSA36.png
Sort by absolute discount: http://i.imgur.com/d7Q6pt1.png

The "big ticket" items only show up in the third one.

**Comment by wchristian** [comment]
In case you haven't outright denied this one yet, i rebased it onto recent work and improved it to show the value with currency formatting.

**Comment by wchristian** [comment]
Since there have been a lot of changes, i've rebased it again, and the branch is now back to being a single commit that will apply cleanly on dev.

If you don't like something about the code, please let me know and i'll change it.

If the value of this isn't clear yet, please also let me know and i'll try to explain it better.

**Comment by wchristian** [comment]
Just a small note: I have in the meantime also fixed it so the absolute discounted value is displayed in the user's currency now.

**Comment by jshackles** [comment]
Thanks, and sorry for not getting to this sooner.  I'd like to add this but I'm going to make a few formatting changes (probably labeling "Discount" and "Absolute Discount" as "Discount (Percentage)" and "Discount (Amount)" to reduce confusion.

Overall I think this should help a lot of people, well done. :+1:

**Comment by wchristian** [comment]
I don't particularly care how it looks as long as it works. Thanks for integrating it! :D

If there are issues with the code in the future, feel free to ping me too.

**Pull request merged**
