### PR TITLE
FEATURE: Show the number of apps on sale

### PR DESCRIPTION
**Pull request by JoiNNN**
* Shows the number of wishlisted apps on sale near the number of
wishlisted apps. I've seen this requested on Steam subreddit, thought it
might be nice to have it in ES.
* Cleaned up space indentations in main CSS file

chrome_2016-04-18_00-17-05

### CODE REVIEW

**Comment by JoiNNN** [comment]
I'm closing this, I've made too many changes, will send another pull request.

**Comment by seeeeew** [comment]
Slightly off topic: What is the red icon next to the install button in your screenshot?

**Comment by JoiNNN** [comment]
@seeeeew That's [Family view](https://support.steampowered.com/kb_article.php?ref=5149-EOPC-9918), an extra layer of protection for accounts...

**Comment by seeeeew** [comment]
Thanks, good to know. Never used Family View myself. ^^

**Pull request closed without merging**
