### PR TITLE
ADD: Currencies CHF, CLP, PEN, COP

### PR DESCRIPTION
**Pull request by seeeeew**
Just a small update. Still working on the improvements to fix the CNY/JPY (¥) problem.

### CODE REVIEW

**Comment by jshackles** [comment]
While a lot of these are factually correct they don't seem to line up with Steam's own formatting of these currencies.  I'll run some more tests and push my own commit to the dev branch for these.  Thanks for the leg up though!

**Comment by seeeeew** [comment]
Your values (15a9ab1bac2271b31408452b146d86694d462058) seem to work, but they're not correct. Can you give me some examples where mine don't work?

**Comment by jshackles** [comment]
COP places should be 0 and CLP hideplaceswhenzero should be true.

These values are used by the parse_currency function to determine actual values of on-page numbers so they have to match exactly the same formatting that Valve uses for these values.  However thanks for bringing this up because on examining a few I noticed that some of the values were wrong in my commit as well and I corrected them.  :+1:   There are getting to be a lot of these to keep track of!

**Comment by seeeeew** [comment]
Your updated values are correct. :+1:

**Pull request closed without merging**
