### PR TITLE
#1009 implementation

### PR DESCRIPTION
**Pull request by owenhsieh**
Users are able to:
1. Hide mixed/negative items.
2. Hide items that price over certain amount.

Right now I don't know how to perfectly distinguish "overwhelmingly negative" and "mostly negative" since it differed from country to country. But I think hide mixed/negative do help a lot.

### CODE REVIEW

**Comment by jshackles** [comment]
I like the options to be able to hide the mixed and negatively reviewed games in search - very useful.

I am having difficulty getting the price filter to work, and I think it's because this line:

`var price = Number(intern[idx-1]);`

where (in my debugging) the value of intern[idx-1] is a dollar amount ie. "$3.99", "$19.99", etc.  I recommend using the parse_currency function that's available and evaluating the value property of what is returned, as this function is designed to handle all of Steam's available currency types.  Just doing some quick and dirty testing, I was able to get it working (I think).

Let me know if you need further clarification @owenhsieh, I would be happy to assist you.

**Comment by owenhsieh** [comment]
thanks! I actually DO have problem dealing with the currency.
I'll fix it as soon as I can.

**Comment by owenhsieh** [comment]
I had changed it using `parse_currency` and it's working in my country.
If you ran into any problem please let me know. Thank you.

**Comment by jshackles** [comment]
This looks great.  I'm going to roll these changes into dev, but I'm going to update a few of the UI elements and language used here before release.  Great work!  :+1:

**Pull request merged**
