### PR TITLE
Added Barter.vg to community profile URLs

### PR DESCRIPTION
**Pull request by Royalgamer06**

### CODE REVIEW

**Comment by Milouzze** [comment]
Hope this gets promoted, that would be a great addition to EnhancedSteam !

**Comment by lillje** [comment]
Definitely a very useful addition!

**Comment by r6d2** [comment]
Nice!

**Comment by jshackles** [comment]
While I'm sure this site is no doubt useful, the site's scope seems to be limited to around 10,000 accounts and only a handful of those accounts are marked as being "active".  Enhanced Steam is used by millions of Steam users and this link would be present on all of the few hundred million Steam profiles for those users.  This means that 99.9% of these clicks would simply direct the users to a "User not found" page which is not very useful to the average user.

Because of this, I'm going to have to decline this PR.

**Comment by Royalgamer06** [comment]
Hmm, this is very unfortunate. But I have an idea. I suggest caching http://barter.vg/u/json/, which contains a list of active users, then only display the link if the user is actually using barter.vg and refresh the list ever so often. It would really be great if those 10K accounts grow to 100K accounts, which I am sure Enhanced Steam can help with that. Like you said the site is no doubt really useful for traders. It will enhance the productivity for traders a lot and a larger user base will really help with that. Besides, is this really an issue about the quantity of active accounts? Many users don't use steamtrades either, yet ES supports that. There are a lot of reasons why barter.vg links would be a great addition. It's another source to determine if an user is trustworthy or not. Having these links added to ES can help us identity impostors that pretend to be a barter user they are not. Clearly a lot of people want to see barter.vg added and hopefully you can reconsider your decline.

**Comment by jshackles** [comment]
The issue isn't the number of users that the site has.  Most if not all of the other sites which provide links on user's profiles will gracefully transition users who do not already have an account.  For example sites like steamtrades or backpack.tf will, upon encountering a user that's unknown to their database, pull that user's info via the Steam API and automatically create an account for that user and display any relevant information to the visitor (along with options for "claiming" the page by signing in with Steam, etc).  

This provides a much better user experience than simply being presented with "Unknown user" and being given a list of active users.  This will also help the site grow organically as users click on people's profiles naturally while using the extension.

**Comment by Royalgamer06** [comment]
Alright, barter is working on this.

**Comment by Luckz** [comment]
https://barter.vg/steam/76561198040672342
(linking to https is preferred but http is ok too; as far as I understand an option in the SteamDB extension anyway forces steamcommunity URLs to be accessed via https)

Btw, SteamGifts also is anything but graceful when a user isn't found (you just get redirected to the front page, which according to your 2014 writeup @ http://www.enhancedsteam.com/faqsprofilelinks.php isn't permitted)


It should also be mentioned that indeed https://github.com/jshackles/Enhanced_Steam/commit/687c094968be7f9a30fa59481bd2e19596b94f46 allows doing it manually - but official support in E.S. certainly is nicer!

**Pull request closed without merging**
