### PR TITLE
ADD: Store page link on badge pages

### PR DESCRIPTION
**Pull request by JoiNNN**
_Resolves #486_

### CODE REVIEW

**Comment by seeeeew** [comment]
If you add something like "resolves #486" to the commit message the issue will be closed automatically once it lands in the main branch. (See https://help.github.com/articles/closing-issues-via-commit-messages/)

**Comment by JoiNNN** [comment]
That's awesome, thanks for the tip 👍

**Comment by seeeeew** [comment]
Sure, no problem! In this case the issues will only be closed when the next version is released, because that's when the code is pushed to the master branch, but at least it's automatic and can't be forgotten. (I assume you checked the page to see all the different wordings you can use.)

**Comment by JoiNNN** [comment]
Sure did check the page, you suggestion seemed appropriate given is not an actual bug, where "fixes" would've been better fit. And "closes" I'd only use for somewhat unrelated issues.

**Comment by seeeeew** [comment]
I usually write "fixes" for fixed bugs, "resolves" for implemented feature requests and "closes" for anything else, e. g. something that just makes an issue obsolete.

**Pull request merged**
