### PR TITLE
Removed a $ by mistake

### PR DESCRIPTION
**Pull request by JoiNNN**
It happened in commit https://github.com/jshackles/Enhanced_Steam/commit/54c93c494c9a994bd663c8deac2ae8ad86b82acb from PR #993

### CODE REVIEW

**Comment by seeeeew** [comment]
Can you amend your commit and reference the broken commit (54c93c494c9a994bd663c8deac2ae8ad86b82acb) in the commit message?

**Comment by seeeeew** [comment]
I meant the actual commit message, since the PR description is only visible on Github. ;)

Try this:
`git checkout missing-ds`
`git commit --amend`
edit commit message
`git push`

**Comment by JoiNNN** [comment]
To honest I'm a bit lost :smile:, I don't use CLI, I'll give a try.

**Comment by seeeeew** [comment]
I'm sure you'll figure it out. Amending should be supported by pretty much every Git tool. :smile:

**Comment by JoiNNN** [comment]
Nope! I'm creating another PR for this, sorry.

**Pull request closed without merging**
