### PR TITLE
fix some of the japanese localization strings

### PR DESCRIPTION
**Pull request by tmokmss**
I corrected some of the Japanese localization strings which did not make sense.

### CODE REVIEW

**Comment by seeeeew** [comment]
Localization is done on Crowdin. You should submit your changes there.
http://translation.enhancedsteam.com/translate/enhanced-steam/4/en-ja

**Comment by tmokmss** [comment]
Oh sorry I didn't notice that.
As I checked Crowdin, I found those poor translations already have a few downvotes and received decent Japanese suggestions instead several years ago.

Could you approve those suggestions?
Thanks.

**Comment by seeeeew** [comment]
No problem, I did the same thing when I started translating. I can only approve german translations, @jshackles needs to approve the japanese ones or appoint a new proofreader for japanese.

**Comment by jshackles** [comment]
@tmokmss if you set up an account on Crowdin and let me know what it is, I can get you the right permissions.  Thanks!

**Comment by tmokmss** [comment]
OK, I can work as a moderator of Japanese translation.
Here is my Crowdin profile: https://crowdin.com/profile/tmokmss
Thanks.

**Comment by jshackles** [comment]
@tmokmss I believe you have to contribute to the project or otherwise "join" it before I can assign you permissions to proofread.  Thanks.

**Comment by tmokmss** [comment]
@jshackles Sorry for inconvenience!
I joined it a minute ago.

**Comment by jshackles** [comment]
Excellent, thank you.

You should have proofreading access to the Japanese translation now.  Let me know if you run into any issues.

**Comment by tmokmss** [comment]
I've done updating and approving the suggestions.
I'm looking forward to a new release of ES someday!
Thanks again.

**Pull request closed without merging**
