### PR TITLE
#719 - Option to hide/remove "Empty Wishlist" button

### PR DESCRIPTION
**Pull request by codymaines**
Achieves feature #719.

Ideally, I wanted to just check the setting in the add_empty_wishlist_buttons function, however the settings do not appear to be available in that context. Alternatively, I wanted to call .remove() on the button in remove_empty_wishlist_button()... but the button is not on the page at time of that method invoking.

So, instead we're adding a flag.

Alternatively (if we didn't want the global var), we could add css to the page in 'remove_empty_wishlist_button'.

### CODE REVIEW

**Comment by JoiNNN** [comment]
Hi @codymaines ,
Nice addition, however, remove_empty_wishlist_button()  shouldn't be needed, just adding the options check it contains to add_empty_wishlist_buttons() should suffice.

**Comment by codymaines** [comment]
@JoiNNN - Thanks. Like I said in my comment, settings (where the options appear to be stored) does not seem to be initialized in add_empty_wishlist_buttons(). When I tried to check there, it's just null. I can't figure out where in the chain it becomes initialized, or how to initialize it.

**Comment by JoiNNN** [comment]
@codymaines the settings are read/initaited in each function (not optimal, I know). Also keep in mind that storage access is asynchronous, meaning you have to wrap the code inside the "storage.get()" call.

So the changes should look like this, I haven't tested it, so please make sure you do...
```
function add_empty_wishlist_buttons() {
	if (is_signed_in && window.location.pathname.startsWith(profile_url)) {
		storage.get(function(settings) {
	 		if (settings.showemptywishlist === undefined) { 
	 			settings.showemptywishlist = true; 
	 			storage.set({'showemptywishlist': settings.showemptywishlist}); 
	 		}

	 		if (settings.showemptywishlist) {
				var empty_buttons = $("<div class='btn_save' id='es_empty_wishlist'>" + localized_strings.empty_wishlist + "</div>");
				$(".save_actions_enabled").filter(":last").after(empty_buttons);
				$("#es_empty_wishlist").click(empty_wishlist);
	 		}
	 	});
	}
}
```

**Comment by codymaines** [comment]
Thanks for your patience! I see now why the async behavior was throwing me off.

I tested and it is working great now. However, why does your suggestion add this condition to the first if statement? 

`&& window.location.pathname.startsWith(profile_url)`

The other 'add_wishlist_*' methods don't seem to test the pathname (except add_wishlist_notes())

Thanks again

**Comment by JoiNNN** [comment]
We use that check to simply make sure the wishlist page you are viewing belongs to you, as it makes no sense to show the "Empty Wishlist" button while viewing other's wishlists. Same with the wishlist notes.

**Comment by jshackles** [comment]
Looks good, thanks @codymaines :+1:

**Pull request merged**
