### PR TITLE
ADD: Profile permalink copy button

### PR DESCRIPTION
**Pull request by JoiNNN**
- added a button to copy profiles permalink with one click

_["Copy to clipboard" icon](https://octicons.github.com/icon/clippy/) (c) GitHub, Inc. [licensed under SIL OFL 1.1](https://github.com/primer/octicons#license)._

### CODE REVIEW

**Comment by seeeeew** [comment]
Nice feature, but I think the commit message should state that clippy.svg is from Github's Octicons.

**Comment by JoiNNN** [comment]
To be honest I wasn't aware of Octicons or that this icon is part of it. I found the icon around the web while looking for an appropriate image.
I see these images are licensed under MIT, if needed @jshackles could incorporate a copy of the licence and/or add credits and their licencing under **Options -> Credits** for these resources.
I'm not really sure how this is supposed to work.

**Comment by seeeeew** [comment]
You absolutely shouldn't use stuff if you don't know the license! This can lead to serious problems.

I'd suggest you close this PR and replace it with one that contains an exact copy of [Octicons' clippy.svg](https://github.com/primer/octicons/blob/master/lib/svg/clippy.svg). Github's Octicons are licensed under the [MIT license](https://github.com/primer/octicons/blob/master/LICENSE). This might still require a license note.

Alternatively you could use the unicode character CLIPBOARD (📋) instead, but that might not work (or look the same) across all browsers and systems.

**Comment by JoiNNN** [comment]
I've replaced the icon and I'll let @jshackles decide further on how to handle this.

**Comment by seeeeew** [comment]
The old icon still exists in the history and the source of the icon still isn't included in the commit message. I think these commits shold be squashed, re-committed with the source in the commit message and submitted as a new PR.

**Pull request closed without merging**
