### PR TITLE
Add lowest price for every item in wishlist

### PR DESCRIPTION
**Pull request by Freelix**
I've edited the "current_lowest_price" on the wishlist page. It is now working properly.

- It shows up for every wishlist item on page load.
The wishlist page will show only 16 wishlist items at once, so we have to call get_price_data() on the scroll event to be able to load every element properly.

- Classname **wishlistRow** is now called **wishlist_row**

### CODE REVIEW

**Comment by Freelix** [comment]
Updated Pull Request with build 9.8

**Comment by jshackles** [comment]
One of the reasons that wishlists have traditionally required price history updates on hover (rather than all at once, as is here) is because we are trying to prevent our API servers from getting overloaded by the requests.  With this code, if someone were to load a wishlist page with several thousand items and scroll to the bottom, it would make several thousand requests at once which a) isn't good for client stability and b) would be taxing on our API servers resources.

**Comment by Freelix** [comment]
Your right, but it only loads 16 wishlist items at once. It would cost a lot only if someone with a thousand items scroll to the bottom of the page. I think it would be convenient for most people though.

**Comment by jshackles** [comment]
Convenient for some, but not for others who get failed requests when the API servers get overloaded.

Enhanced Steam is used by over 400,000 users every week, the odds of one of them loading a super-large wishlist would be high.  Even wishlist pages loading 16 requests at once, multiplied out by that many users would be a problem.

**Comment by Freelix** [comment]
True, I'll keep that in mind the next time. Thanks !

**Pull request closed without merging**
