### PR TITLE
highlight_node() optimizations

### PR DESCRIPTION
**Pull request by JoiNNN**
* offloaded the CSS aplied to each node to an inlined "style" block and to file

### CODE REVIEW

**Comment by jshackles** [comment]
I'm doing some testing on this but it seems that replacing `$(node).find("img").css("opacity", "1");` with pure CSS is having some unexpected consequences in that images are only given this opacity if they fall directly below the es_highlighted node in the DOM.  A lot of times, these images are wrapped and it appears that with this change doesn't account for that.  As a result, images inside the .es_highlighted containers do not have the correct opacity when highlighting is enabled.

**Comment by JoiNNN** [comment]
I am aware of that bug but it was there before and I wasn't sure if I should fix it or let it be. The opacity is inherited from one of Steam's CSS file. I can fix that and resubmit the PR.

**Comment by jshackles** [comment]
Ideally, any images loaded in a highlighted container would be at full opacity.  Steam's CSS reduces the  image opacity because it overlays their own flag, which we remove.

I know it's a current bug in the dev build as is that the opacity is incorrect for items in the homepage tabs, but everything else (mainly, search results) have the correct opacity as far as I can tell.

**Comment by JoiNNN** [comment]
Well, turns out I was missing a "," in the CSS :disappointed:

**Pull request closed without merging**
