### PR TITLE
ADD: Custom gift card amount

### PR DESCRIPTION
**Pull request by dpeukert**
There's one problem I'm not sure how to solve and that is how to display the input and the currency symbol. I've come up with two solutions, but either one of those only works for one position of the currency symbol (before/after the input). Any ideas?

variant1
variant2

### CODE REVIEW

**Comment by jshackles** [comment]
The input box looks pretty strange at a diagonal, and looks out of place in the second picture.  I was planning on adding this feature and creating the input box either above or beneath the image and having the amount of the image change accordingly.

Also, even though it might not make as logical sense, we should probably just add the translation to the existing group without changing that group's name.  Changing the name will require that translators re-submit those strings again even though they're the same.

**Comment by dpeukert** [comment]
What about this?
image

**Comment by jshackles** [comment]
That looks really good

**Comment by dpeukert** [comment]
Thanks!

**Pull request merged**
