### PR TITLE
FIX: Repetitive code

### PR DESCRIPTION
**Pull request by JoiNNN**

### CODE REVIEW

**Comment by fadillzzz** [comment]
I'd move the regex construction out of the iteration. The main reason why I took it out of there in the first place was to optimise the execution a bit further, so that opening a store page can be as smooth as possible, without any freezes.

```
var replace_strings = [];

[
    "- Complete Pack",
    "Standard Edition",
    "Steam Store and Retail Key",
    "- Hardware Survey",
    "ComputerGamesRO -",
    "Founder Edition",
    "Retail( Key)?",
    "Complete$",
    "Free$",
    "(RoW)",
    "ROW",
    ":",
].forEach(function (str) {
    replace_strings.push(new RegExp(str, "ig"));
});
```

**Comment by JoiNNN** [comment]
I really didn't thought generating the regex when iterating would make any difference, but if you tested and it runs better then it's all good. To me it looked like you forgot to change back the code after doing some digging for a fix.
I will edit the PR with your suggestion, thanks.

**Comment by fadillzzz** [comment]
To be honest, I was a bit surprised as well. At first, I made that change on a whim and thinking that it's just micro-optimisation and wouldn't yield any result. But after testing the page load a few times with the regex built in and out of the iteration, turns out it really does contribute to the browser freeze.

**Comment by JoiNNN** [comment]
After thinking a bit about the performance impact you noticed it I just realized my mistake 😄 and I'm no longer surprised it impacted performance, since I was (re)compiling each regex string over and over again with every iteration.

**Pull request merged**
