### PR TITLE
ADD: Dreamgame store prices

### PR DESCRIPTION
**Pull request by JoiNNN**

### CODE REVIEW

**Comment by jshackles** [comment]
Unfortunately, IsThereAnyDeal.com doesn't support this store in their API so these changes wouldn't actually do anything until that happened.

**Comment by JoiNNN** [comment]
I've noticed another extension pulling prices from this website via ITAD, so I made a quick test and everything worked as expected.
I've just tested it again by only selecting Dreamgame store for price comparison and it works.
adadd

**Comment by jshackles** [comment]
Interesting - I don't think this is live yet for all regions (not working in the US) and the store code isn't exposed in their internal API.  I will reach out to them to investigate.

**Comment by jshackles** [comment]
I got word from IsThereAnyDeal that his store is now working for most regions.  :+1:

**Pull request merged**
