### PR TITLE
Fixes various issues with sums on market front page

### PR DESCRIPTION
**Pull request by fadillzzz**
image

### CODE REVIEW

**Comment by fadillzzz** [comment]
This *might* fix #979 as well

**Comment by VladimirMangos** [comment]
I not see problem from  #979 long time. Possible it's fixed already.

**Comment by fadillzzz** [comment]
@VladimirMangos Cool, thanks for the update.

**Comment by fadillzzz** [comment]
ping @jshackles

**Comment by jshackles** [comment]
Sorry it took so long to review this PR.  Everything looks good, thanks! :+1:

**Pull request merged**
