### PR TITLE
Added link to app's page on SteamSpy

### PR DESCRIPTION
**Pull request by number213**
On app's page in store, add a link to app's entry on [SteamSpy.com](http://steamspy.com/)

### CODE REVIEW

**Comment by JoiNNN** [comment]
We already pull and display data from SteamSpy and there is also a link to SteamSpy for each app.

**Comment by jshackles** [comment]
Yes, not only is there a link to Steamspy on each page, but it also pulls the pertinent information for that game and displays it there.  This requires the ES API which proxies and caches these requests - the design and placement was approved by Sergey Galyonkin himself.

**Comment by number213** [comment]
Like I said, ES API doesn't work unless I use US VPN, so I see no info on the page. Maybe your ISP is blocking access from Russia.
Plus, I would rather see a link at the top of the page, so I wouldn't have to scroll down, [like so (pic)](https://i.sli.mg/VImoOC.png).

**Comment by jshackles** [comment]
The ES API servers are behind a Cloudflare CDN that may occasionally check that the traffic isn't originating from a known spammer's IP address or one linked to the spread of malware.  Sorry it isn't working for you.

The beauty of open source software such as this is that you're free to customize the extension however you'd like to fit your own needs.

**Pull request closed without merging**
